update role set name = 'SUPER-ADMIN' where id = 1;
update role set name = '权限点管理员 - OA' where id = 2;
update role set name = 'CPO' where id = 4;
update role set name = 'CMO' where id = 5;
update role set name = 'CFO' where id = 6;
update role set name = 'CTO' where id = 9;
update role set name = 'Human Resources Director' where id = 11;
update role set name = '权限点管理员 - CHIDORI' where id = 16;
update role set name = 'CEO' where id = 29;
update role set name = 'Web开发 - OA' where id = 31;
update role set name = '测试 - OA' where id = 36;
update role set name = '后端Lead - 内部工具' where id = 40;
update role set name = 'Backend Development - OA' where id = 41;
update role set name = 'Web开发 - Chidori' where id = 56;
update role set name = '产品经理 - OA - Lead' where id = 61;
update role set name = '产品经理 - Chidori - Lead' where id = 62;
update role set name = '产品经理 - 财务系统 - Lead' where id = 69;
update role set name = '后端开发 - Chidori' where id = 71;
update role set name = 'Indonesia Regional Manager' where id = 86;
update role set name = '权限点管理员 - ADMIN 洋钱罐' where id = 117;
update role set name = '权限点管理员 - ADMIN 六六钱庄' where id = 119;
update role set name = '权限点管理员 - ADMIN 资金资产' where id = 120;
update role set name = '权限点管理员 - ADMIN 存管系统' where id = 121;
update role set name = '权限点管理员 - ADMIN 通用工具' where id = 122;
update role set name = 'Finance Director' where id = 125;
update role set name = '权限点管理员 - ADMIN 风控' where id = 156;
update role set name = '权限点管理员 - ADMIN 洋钱罐借款' where id = 157;
update role set name = '权限点管理员 - ADMIN 外呼管理' where id = 174;
update role set name = '权限点管理员 - MAYURI' where id = 176;
update role set name = '运维 Lead' where id = 199;
update role set name = '权限点管理员 - ADMIN 报表系统' where id = 206;
update role set name = 'Indonesia Product Manager' where id = 223;
update role set name = '数仓开发 - Lead' where id = 233;
update role set name = 'IT审计' where id = 246;
update role set name = '后端开发 - 企业系统 - Lead' where id = 249;
update role set name = 'Web - Lead - 国内' where id = 252;
update role set name = 'Web - Lead - 海外&内部工具' where id = 253;
update role set name = '产品经理 - OA' where id = 256;
update role set name = 'Indonesia Customer Service Supervisor' where id = 272;
update role set name = 'Indonesia Customer Service' where id = 273;
update role set name = 'Indonesia Sales Supervisor' where id = 274;
update role set name = 'Indonesia Sales' where id = 275;
update role set name = 'Indonesia Capital' where id = 276;
update role set name = '权限点管理员 - VOTE' where id = 285;
update role set name = '权限点管理员 - YTalk呼叫平台' where id = 289;
update role set name = 'Indonesia Manual Verification' where id = 301;
update role set name = 'Southeast Asia Risk Control - Lead' where id = 315;
update role set name = '产品经理 - 保险 - Lead' where id = 328;
update role set name = '权限点管理员 - TECH' where id = 354;
update role set name = 'Indonesia Administrative Supervisor' where id = 410;
update role set name = '权限点管理员 - 海外 tech 系统' where id = 443;
update role set name = 'Indonesia Administration' where id = 463;
update role set name = '权限点管理员 - DW' where id = 472;
update role set name = 'Indonesia Senior Risk Control (Strategy)' where id = 480;
update role set name = '权限点管理员 - YChat客服系统' where id = 484;
update role set name = 'Indonesia Market Operations' where id = 544;
update role set name = '权限点管理员 - 中收ADMIN' where id = 564;
update role set name = 'Indonesia Basic' where id = 586;
update role set name = '权限点管理员 - SPIDER系统' where id = 589;
update role set name = 'Indonesia Verification Quality Inspector' where id = 591;
update role set name = 'Indonesia Audit Supervisor' where id = 592;
update role set name = 'Modify Bank Card' where id = 608;
update role set name = 'VIP RM' where id = 614;
update role set name = 'Indonesia Project Operations Manager' where id = 616;
update role set name = 'Indonesia Project Operations Supervisor' where id = 617;
update role set name = 'Indonesia Project Operations' where id = 618;
update role set name = '权限点管理员 - 印尼OA' where id = 668;
update role set name = 'Indonesia Technical Manager' where id = 672;
update role set name = 'Indonesia Technology' where id = 673;
update role set name = 'Local-risk team' where id = 690;
update role set name = 'Legal Specialist-Indonesia Fintopia' where id = 694;
update role set name = 'ID Senior Product Manger' where id = 701;
update role set name = 'Internal Audit-Indonesia Fintopia' where id = 703;
update role set name = 'Indo OA test' where id = 706;
update role set name = 'Indo OA Finance Test' where id = 707;
update role set name = 'Indo OA HR Test' where id = 708;
update role set name = 'Accounting - Indonesia Fintopia' where id = 713;
update role set name = 'Cashier - Indonesia Fintopia' where id = 714;
update role set name = 'Project operation-Indonesia Fintopia' where id = 715;
update role set name = 'Legal specialist1-Indonesia Fintopia' where id = 719;
update role set name = 'Seal management-Indonesia Fintopia' where id = 720;
update role set name = 'Employee loan-Indonesia Fintopia' where id = 728;
update role set name = '权限点管理员 - sea风控决策引擎' where id = 738;
update role set name = 'ID User Account Management' where id = 762;
update role set name = 'Employee Relations Specialist-Indonesia Fintopia' where id = 769;
update role set name = 'Fee Application - Indonesian Finance' where id = 770;
update role set name = 'Credit Operation BD-Indonesia Fintopia' where id = 771;
update role set name = 'Credit Operations Supervisor-Indonesia Fintopia' where id = 772;
update role set name = 'HR-Indonesia Fintopia' where id = 773;
update role set name = 'Risk -Indonesia Fintopia' where id = 775;
update role set name = 'Product Manager-Indonesia Fintopia' where id = 776;
update role set name = 'Contract & Fee Application-Indonesia Fintopia' where id = 777;
update role set name = 'Marketing Operation-Indonesia Fintopia' where id = 778;
update role set name = 'Project Operations Supervisor-Indonesia Fintopia' where id = 779;
update role set name = 'GA &Admin Supervisor-Indonesia Fintopia' where id = 780;
update role set name = 'Admin Management-Indonesia Fintopia' where id = 781;
update role set name = 'Basic-Indonesia Fintopia' where id = 782;
update role set name = 'Basic Finance-Indonesia Fintopia' where id = 783;
update role set name = 'HRM-Indonesia Fintopia' where id = 792;
update role set name = '内控流程BP' where id = 799;
update role set name = '权限点管理员 - 大鱼平台(RTA)' where id = 800;
update role set name = '初级产品经理 - OA' where id = 824;
update role set name = 'Indo OA HR Test - Indonesia Fintopia' where id = 849;
update role set name = 'HR Manager' where id = 857;
update role set name = 'ID IT Support Manager' where id = 860;
update role set name = 'ID IT Support' where id = 861;
update role set name = 'Workflow handover-Indonesia Fintopia' where id = 871;
update role set name = 'HR Indonesia Approval' where id = 891;
update role set name = '权限点管理员 - 菲律宾SmartAP' where id = 894;
update role set name = 'Fee Application - Indonesian PM' where id = 901;
update role set name = 'OA产品 - 财务合同人力' where id = 913;
update role set name = 'HRBP - Indonesia' where id = 915;
update role set name = 'Permission Review Director' where id = 927;
update role set name = 'OM Permission Review' where id = 928;
update role set name = '权限点管理员 - 新海鱼平台(RTA)' where id = 931;
update role set name = '权限点管理员 - 印尼海鱼平台(RTA)' where id = 932;
update role set name = '权限点管理员 - 印尼风控决策Local' where id = 950;
update role set name = 'Indonesia Risk control management' where id = 952;
update role set name = '权限点管理员 - Ad-Hoc平台' where id = 966;
update role set name = '权限点管理员 - yqg-chat' where id = 968;
update role set name = '反欺诈leader' where id = 970;
update role set name = '后端开发 - 数据安全 - Lead' where id = 973;
update role set name = '后端开发 - 基础服务中台 - Lead' where id = 977;
update role set name = '权限点管理员 - 新版权限管理crane' where id = 1007;
update role set name = '洋钱罐借款AB实验产研测' where id = 1029;
update role set name = 'risk-super admin' where id = 1046;
update role set name = '权限点管理员 - yqg-mod搭投平台' where id = 1054;
update role set name = '测试-临时预算币种统一使用（有效期9.29）' where id = 1068;
update role set name = '权限点管理员 - 人行征信ADMIN' where id = 1084;
update role set name = '权限点管理员 - 通知admin' where id = 1117;
update role set name = 'ID Compliance' where id = 1118;
update role set name = '权限点管理员 - 数据平台-EMR环境' where id = 1142;
update role set name = 'person-query Indonesi' where id = 1170;