update role set name = 'Permission Point Administrator - OA' where id = 2;
update role set name = 'Permission Point Administrator - CHIDORI' where id = 16;
update role set name = 'Web Development - OA' where id = 31;
update role set name = 'Testing - OA' where id = 36;
update role set name = 'Backend Lead - Internal Tools' where id = 40;
update role set name = 'Web Development - Chidori' where id = 56;
update role set name = 'Product Manager - OA - Lead' where id = 61;
update role set name = 'Product Manager - Chidori - Lead' where id = 62;
update role set name = 'Product Manager - Financial System - Lead' where id = 69;
update role set name = 'Backend Development - Chidori' where id = 71;
update role set name = 'Permission Point Administrator - ADMIN Yangqian罐' where id = 117;
update role set name = 'Permission Point Administrator - ADMIN Liuliqianzhuang' where id = 119;
update role set name = 'Permission Point Administrator - ADMIN Capital Assets' where id = 120;
update role set name = 'Permission Point Administrator - ADMIN Deposit System' where id = 121;
update role set name = 'Permission Point Administrator - ADMIN General Tools' where id = 122;
update role set name = 'Permission Point Administrator - ADMIN Risk Control' where id = 156;
update role set name = 'Permission Point Administrator - ADMIN Yangqian罐 Borrowing' where id = 157;
update role set name = 'Permission Point Administrator - ADMIN Outbound Call Management' where id = 174;
update role set name = 'Permission Point Administrator - MAYURI' where id = 176;
update role set name = 'Operations Lead' where id = 199;
update role set name = 'Permission Point Administrator - ADMIN Reporting System' where id = 206;
update role set name = 'Data Warehouse Development - Lead' where id = 233;
update role set name = 'IT Audit' where id = 246;
update role set name = 'Backend Development - Enterprise System - Lead' where id = 249;
update role set name = 'Web - Lead - Domestic' where id = 252;
update role set name = 'Web - Lead - Overseas & Internal Tools' where id = 253;
update role set name = 'Product Manager - OA' where id = 256;
update role set name = 'Permission Point Administrator - VOTE' where id = 285;
update role set name = 'Permission Point Administrator - YTalk Call Platform' where id = 289;
update role set name = 'Product Manager - Insurance - Lead' where id = 328;
update role set name = 'Permission Point Administrator - TECH' where id = 354;
update role set name = 'Permission Point Administrator - Overseas Tech System' where id = 443;
update role set name = 'Permission Point Administrator - DW' where id = 472;
update role set name = 'Permission Point Administrator - YChat Customer Service System' where id = 484;
update role set name = 'Permission Point Administrator - Middle Revenue ADMIN' where id = 564;
update role set name = 'Permission Point Administrator - SPIDER System' where id = 589;
update role set name = 'Permission Point Administrator - Indonesian OA' where id = 668;
update role set name = 'Permission Point Administrator - Sea Risk Control Decision Engine' where id = 738;
update role set name = 'Internal Control Process BP' where id = 799;
update role set name = 'Permission Point Administrator - DaYu Platform (RTA)' where id = 800;
update role set name = 'Junior Product Manager - OA' where id = 824;
update role set name = 'Permission Point Administrator - Philippine SmartAP' where id = 894;
update role set name = 'OA Product - Finance Contract HR' where id = 913;
update role set name = 'Permission Point Administrator - New Sea Fish Platform (RTA)' where id = 931;
update role set name = 'Permission Point Administrator - Indonesian Sea Fish Platform (RTA)' where id = 932;
update role set name = 'Permission Point Administrator - Indonesian Risk Control Decision Local' where id = 950;
update role set name = 'Permission Point Administrator - Ad-Hoc Platform' where id = 966;
update role set name = 'Permission Point Administrator - yqg-chat' where id = 968;
update role set name = 'Anti-Fraud Leader' where id = 970;
update role set name = 'Backend Development - Data Security - Lead' where id = 973;
update role set name = 'Backend Development - Basic Service Platform - Lead' where id = 977;
update role set name = 'Permission Point Administrator - New Copyright Management Crane' where id = 1007;
update role set name = 'Yangqianguan Borrowing AB Experimental R&D Test' where id = 1029;
update role set name = 'Permission Point Administrator - yqg-mod Investment Platform' where id = 1054;
update role set name = 'Testing - Temporary Budget Currency Unified Use (Valid until 9.29)' where id = 1068;
update role set name = 'Permission Point Administrator - People Bank of China Credit ADMIN' where id = 1084;
update role set name = 'Permission Point Administrator - Notification ADMIN' where id = 1117;
update role set name = 'Permission Point Administrator - Data Platform - EMR Environment' where id = 1142;
