update role set name = '权限点管理员 - OA' where id = 2;
update role set name = '权限点管理员 - CHIDORI' where id = 16;
update role set name = 'Web开发 - OA' where id = 31;
update role set name = '测试 - OA' where id = 36;
update role set name = '后端Lead - 内部工具' where id = 40;
update role set name = 'Web开发 - Chidori' where id = 56;
update role set name = '产品经理 - OA - Lead' where id = 61;
update role set name = '产品经理 - Chidori - Lead' where id = 62;
update role set name = '产品经理 - 财务系统 - Lead' where id = 69;
update role set name = '后端开发 - Chidori' where id = 71;
update role set name = '权限点管理员 - ADMIN 洋钱罐' where id = 117;
update role set name = '权限点管理员 - ADMIN 六六钱庄' where id = 119;
update role set name = '权限点管理员 - ADMIN 资金资产' where id = 120;
update role set name = '权限点管理员 - ADMIN 存管系统' where id = 121;
update role set name = '权限点管理员 - ADMIN 通用工具' where id = 122;
update role set name = '权限点管理员 - ADMIN 风控' where id = 156;
update role set name = '权限点管理员 - ADMIN 洋钱罐借款' where id = 157;
update role set name = '权限点管理员 - ADMIN 外呼管理' where id = 174;
update role set name = '权限点管理员 - MAYURI' where id = 176;
update role set name = '运维 Lead' where id = 199;
update role set name = '权限点管理员 - ADMIN 报表系统' where id = 206;
update role set name = '数仓开发 - Lead' where id = 233;
update role set name = 'IT审计' where id = 246;
update role set name = '后端开发 - 企业系统 - Lead' where id = 249;
update role set name = 'Web - Lead - 国内' where id = 252;
update role set name = 'Web - Lead - 海外&内部工具' where id = 253;
update role set name = '产品经理 - OA' where id = 256;
update role set name = '权限点管理员 - VOTE' where id = 285;
update role set name = '权限点管理员 - YTalk呼叫平台' where id = 289;
update role set name = '产品经理 - 保险 - Lead' where id = 328;
update role set name = '权限点管理员 - TECH' where id = 354;
update role set name = '权限点管理员 - 海外 tech 系统' where id = 443;
update role set name = '权限点管理员 - DW' where id = 472;
update role set name = '权限点管理员 - YChat客服系统' where id = 484;
update role set name = '权限点管理员 - 中收ADMIN' where id = 564;
update role set name = '权限点管理员 - SPIDER系统' where id = 589;
update role set name = '权限点管理员 - 印尼OA' where id = 668;
update role set name = '权限点管理员 - sea风控决策引擎' where id = 738;
update role set name = '内控流程BP' where id = 799;
update role set name = '权限点管理员 - 大鱼平台(RTA)' where id = 800;
update role set name = '初级产品经理 - OA' where id = 824;
update role set name = '权限点管理员 - 菲律宾SmartAP' where id = 894;
update role set name = 'OA产品 - 财务合同人力' where id = 913;
update role set name = '权限点管理员 - 新海鱼平台(RTA)' where id = 931;
update role set name = '权限点管理员 - 印尼海鱼平台(RTA)' where id = 932;
update role set name = '权限点管理员 - 印尼风控决策Local' where id = 950;
update role set name = '权限点管理员 - Ad-Hoc平台' where id = 966;
update role set name = '权限点管理员 - yqg-chat' where id = 968;
update role set name = '反欺诈leader' where id = 970;
update role set name = '后端开发 - 数据安全 - Lead' where id = 973;
update role set name = '后端开发 - 基础服务中台 - Lead' where id = 977;
update role set name = '权限点管理员 - 新版权限管理crane' where id = 1007;
update role set name = '洋钱罐借款AB实验产研测' where id = 1029;
update role set name = '权限点管理员 - yqg-mod搭投平台' where id = 1054;
update role set name = '测试-临时预算币种统一使用（有效期9.29）' where id = 1068;
update role set name = '权限点管理员 - 人行征信ADMIN' where id = 1084;
update role set name = '权限点管理员 - 通知admin' where id = 1117;
update role set name = '权限点管理员 - 数据平台-EMR环境' where id = 1142;