@startuml
skinparam sequenceMessageAlign right
title Crane-tableau报表申请-发起

actor 用户 as create

entity crane数据校验 as crane_check

entity crane新建业务数据 as crane_insert_table

entity OA系统 as oa


create -> crane_check : 点击“提交申请”
crane_check -> create : 数据校验失败，报错提示信息
crane_check -> crane_insert_table : 数据校验成功，新建表数据

crane_insert_table -> oa : 请求OA发起流程
oa -> crane_insert_table : OA报错，crane数据回滚，提示用户失败
crane_insert_table -> create : 发起审批失败，提示用户失败

oa -> crane_insert_table : OA成功/审批回调，crane数据更新flow_id、flow_statue
crane_insert_table -> create : 发起审批成功，提示用户成功

@enduml