@startuml
skinparam sequenceMessageAlign right
title 流程过程

participant 流程发起 as create
participant 流程结束 as end order 100

actor 业务侧发起 as business_create
actor 财务会计 as accountant1
actor 指定审批合作人 as specil_number
actor 财务会计 as accountant2
actor 总裁办 as presidentOffice
actor 业务侧 as business_end


create -> business_create : 用户点击“新建”按钮
business_create -> create : 可撤销
business_create -> accountant1 : 新建发起表单
accountant1 -> accountant1 : 拒绝
accountant1 -> business_create : 驳回修改
accountant1 -> specil_number : 通过：填写2307编码等附件表单
specil_number -> specil_number : 拒绝
specil_number -> accountant1 : 驳回修改
specil_number -> business_create : 驳回修改

specil_number -> accountant2 : 通过：审核附件信息
accountant2 -> accountant2 : 拒绝
accountant2 -> specil_number : 驳回修改
accountant2 -> accountant1 : 驳回修改
accountant2 -> business_create : 驳回修改

accountant2 -> presidentOffice : 通过：审核付款单结清状态
presidentOffice -> presidentOffice : 拒绝
presidentOffice -> accountant2 : 驳回修改
presidentOffice -> specil_number : 驳回修改
presidentOffice -> accountant1 : 驳回修改
presidentOffice -> business_create : 驳回修改

presidentOffice -> business_end :通过：上传盖章版扫描附件
business_end -> business_end :拒绝
business_end -> presidentOffice :驳回修改
business_end -> accountant2 :驳回修改
business_end -> specil_number :驳回修改
business_end -> accountant1 :驳回修改
business_end -> business_create :驳回修改

business_end -> end:通过：填写OR单、OR附件
@enduml